apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-demo
    component:  spring-boot-demo
    tier: backend
  name:  spring-boot-demo-dep
  namespace: kubesphere-sample-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-demo
      component: spring-boot-demo
      tier: backend
  template:
    metadata:
      labels:
        app: spring-boot-demo
        component: spring-boot-demo
        tier: backend
    spec:
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BUILD_NUMBER
          imagePullPolicy: Always
          name: spring-boot-demo
          ports:
            - containerPort: 8089
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      imagePullSecrets:
        - name: docker-registrykey
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30